# Generated by Django 4.2.1 on 2025-01-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentschedule',
            old_name='service_fee_component',
            new_name='service_fee',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='service_fee',
        ),
    ]
