# Generated by Django 5.1.4 on 2025-01-06 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='ledger',
            name='control_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='mcoop_app.loan'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the transaction.'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Loan Release', 'Loan Release'), ('Loan Payment', 'Loan Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(choices=[('Education', 'Education'), ('Medical/Emergency', 'Medical/Emergency'), ('House Construction', 'House Construction'), ('Commodity/Appliances', 'Commodity/Appliances'), ('Utility Services', 'Utility Services'), ('Others', 'Others')], default='Education', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Paid-off', 'Paid-off')], default='Ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='pstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widower', 'Widower'), ('Separated', 'Separated')], default='Single', max_length=50),
        ),
    ]
