# Generated by Django 4.2.1 on 2025-01-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='installment_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
