# Generated by Django 4.2.1 on 2025-01-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='f4f1b', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
