# Generated by Django 4.2.1 on 2025-01-20 04:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0002_rename_service_fee_component_paymentschedule_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loanable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
