# Generated by Django 5.1.4 on 2025-01-15 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0002_paymentschedule_installment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='mcoop_app.loan'),
        ),
    ]
