# Generated by Django 4.2.1 on 2025-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0002_alter_ledger_options_remove_ledger_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={},
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='control_number',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='ledger',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
