# Generated by Django 5.1.4 on 2025-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0003_payment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='co_maker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='relationship',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
