# Generated by Django 5.1.4 on 2025-01-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0003_alter_ledger_options_remove_ledger_control_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='loan_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency')], default='Regular', max_length=20),
        ),
    ]
