# Generated by Django 5.1.4 on 2025-01-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0003_loan_loanable_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loanable_amount',
        ),
    ]
