# Generated by Django 5.1.4 on 2025-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0004_remove_loan_loanable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tin',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
    ]
