# Generated by Django 5.1.4 on 2025-01-08 11:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0004_paymentschedule_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='ann_com',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='id_no',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='valid_id',
            field=models.CharField(choices=[('Philippine Passport', 'Philippine Passport'), ('Drivers License', 'Drivers License'), ('SSS ID', 'SSS ID'), ('GSIS ID', 'GSIS ID'), ('TIN ID', 'TIN ID'), ('Postal ID', 'Postal ID'), ('Voters ID', 'Voters ID'), ('PhilHealth ID', 'PhilHealth ID'), ('National ID', 'National ID')], default='TIN ID', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='zip_code',
            field=models.CharField(blank=True, default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.03'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='pstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('In a relationship', 'In a relationship'), ('Engaged', 'Engaged'), ('Baak', 'Baak')], default='Single', max_length=50),
        ),
    ]
