# Generated by Django 4.2.1 on 2025-01-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0005_alter_loan_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='d57e6', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
