# Generated by Django 5.1.4 on 2025-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0006_member_mem_co'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='in_dep',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20),
        ),
    ]
