# Generated by Django 4.2.1 on 2025-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0006_alter_loan_control_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentschedule',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='37c76', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
