# Generated by Django 5.1.4 on 2025-01-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0007_member_in_dep_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='5c3a', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='ann_com',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='in_dep',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='tin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(blank=True, default='2616', max_length=100),
        ),
    ]
