# Generated by Django 5.1.4 on 2025-01-21 04:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0008_alter_loan_control_number_alter_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='ann_com',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_no',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='in_dep',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='tin',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(blank=True, default='0000', max_length=100),
        ),
    ]
