# Generated by Django 5.1.4 on 2025-01-22 02:00

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0009_alter_loan_control_number_alter_member_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='penalty_rate',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='installment_order',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='interest_amount',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='service_fee',
        ),
        migrations.AddField(
            model_name='loan',
            name='admincost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='cisp',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='notarial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='advance_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='received_amnt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='under_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admincost_r',
            field=models.DecimalField(decimal_places=2, default=Decimal('240.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notarialfee_r',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='annual_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='in_dep',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='tin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(blank=True, default='2616', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
