# Generated by Django 5.1.4 on 2025-01-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0010_remove_loan_interest_rate_remove_loan_penalty_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='co_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='relationships',
            field=models.CharField(default='Brother', max_length=100),
        ),
    ]
