# Generated by Django 4.2.1 on 2025-01-22 20:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0011_loan_co_make_loan_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='co_make',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='relationships',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.08'), max_digits=5, verbose_name='Interest Rate'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='notarialfee_r',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.02'), max_digits=5, verbose_name='Penalty Rate'),
        ),
    ]
