# Generated by Django 5.1.4 on 2025-01-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0011_loan_co_make_loan_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='88be1', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
